# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: About me
email: jasonye100@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I will host my interest and hobbies.
  To give you a better understanding of who I am and what I enjoy
  here are some images to help you visualize!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jasonye.net/" # the base hostname & protocol for your site
instragram_username: jason
github_username:  jasonye1

# Build settings
markdown: kramdown
